### ISSUE TITLE
Doc / code defaults mismatch

### ISSUE THREAD

**Issue by superbock** [olemb/mido#103]
There's a mismatch between the docs and code regarding default values used for time signature. [The docs say the default is 4/4](http://mido.readthedocs.io/en/latest/meta_message_types.html?highlight=signature#time-signature-0x58), whereas [the corresponding code uses 4/2](https://github.com/olemb/mido/blob/master/mido/midifiles/meta.py#L347).

```
mido.MetaMessage('time_signature')
<meta message time_signature numerator=4 denominator=2 clocks_per_click=24 notated_32nd_notes_per_beat=8 time=0>
```

Although I am not a big fan of changing the default values in the code, I think this is exactly what should be done since 4/4 is definitely more common than 4/2 time signature.

**Comment by cjappl** [comment]
Would this need to be accompanied by a major version bump? It may break existing code

**Comment by olemb** [comment]
The default signature was always supposed to be 4/4 so this is a bug. I think we should just apply your patch and add a note to the documentation.

As for version bump I'm not sure. It seems a bit excessive to bump the version for such a small change.

**Comment by cjappl** [comment]
Pull request looks good to me!

**Comment by olemb** [comment]
OK, I've merged it and added a note to the docs. Thanks!
