### ISSUE TITLE
convert piano pedal from 0 to 127 and 127 to zero

### ISSUE THREAD

**Issue by seanwayland** [olemb/mido#106]
Hi all,
I hope it's appropriate to raise an "issue" like this .. 
I couldn't find a mailing list .. I emailed this to olemb .. 
I am trying to iterate over a bunch of midi files and reverse the
polarity of the sustain pedal messages. When the control change 064
message is 0 I want it to be 127 and vise versa ..
I have a lot of files to fix and I thought a little python script might do it ..
I don't quite understand your documentation ..
Is this possible ?
I wrote a little script but it doesn't do much at the moment .. ..

import mido
from mido import Message, MidiFile, MidiTrack
mid = mido.MidiFile('DarkSoul_110BPM_Gmin_Groove1.mid')
for msg in mid.play():

    if msg.type == 'control_change':

       ped = msg.value

       pedfix = abs(ped-127)

       msg = msg.copy( value = pedfix )

mid.save('new_song.mid')

Let me know if you have any ideas!
Thanks for your help in advance ..
Best Sean

**Comment by olemb** [comment]
Hi Sean,

Your code creates a new message but doesn't update the track. Something like this should work:

```
mid = mido.MidiFile('DarkSoul_110BPM_Gmin_Groove1.mid')
for msg in mid.play():
    for track in mid.tracks:
        for i, msg in enumerate(track):
            if msg.type == 'control_change':
                ped = msg.value
                pedfix = abs(ped-127)
                # Replace message in track.                                     
                track[i] = msg.copy(value=pedfix)

mid.save('new_song.mid')
```

Note that I'm explicitly looping over the tracks to get the actual message. (`mid.play()` will do some tempo computations that change the `time` values and also merge everything into one track.)

**Comment by seanwayland** [comment]
Hi Ole,
Thanks very much for your reply! 
I have this .py file (below) saved in the same directory as the midi file . If I run it from idle or call the program directly from the terminal it runs but nothing happens. I have to close the terminal to quit the program .. I tried putting ./ or various pathnames in the mid.save and have searched my filesystem but can't find the saved file anywhere .. Let me know if I am missing something obvious! Thanks Sean

import mido
from mido import Message, MidiFile, MidiTrack
mid = mido.MidiFile('DarkSoul_110BPM_Gmin_Groove1.mid')
for msg in mid.play():
    for track in mid.tracks:
        for i, msg in enumerate(track):
            if msg.type == 'control_change':
                ped = msg.value
                pedfix = abs(ped-127)
                # Replace message in track.
                track[i] = msg.copy(value=pedfix)

mid.save('new_song.mid')

**Comment by seanwayland** [comment]
This program hangs too even with a sys.exit() at the end .. 
It's like the for msg line is generating an endless loop .. 
It just prints all the messages out in the file and then hangs .. 
I am running from idle using python 2.7.13 

import mido
from mido import Message, MidiFile, MidiTrack
import sys
mid = mido.MidiFile('DarkSoul_110BPM_Gmin_Groove1.mid')
for msg in mid.play():
    print(msg)
#   for track in mid.tracks:
#       for i, msg in enumerate(track):
#            if msg.type == 'control_change':
#                ped = msg.value
#               pedfix = abs(ped-127)
#               # Replace message in track.
#                track[i] = msg.copy(value=pedfix)
#                print(msg)


#mid.save('new_song.mid')

sys.exit()

**Comment by olemb** [comment]
If you don't specify a path the file should be saved to the current working directory which you can find by doing this:

```
import os
print(os.getcwd())
```

BTW, are you using Windows?

**Comment by olemb** [comment]
Your example code just went bold. :) The hash character will mark the text as bold. You can surround your code example with triple backticks:

    ```
    # Comment.
    print('Code example')
    ```

or indent the code 4 spaces (which I find less cut and paste friendly so I always use the triple backticks).

**Comment by seanwayland** [comment]
Thanks Ole! 
I added the backticks ! I am pretty new to git ! 
I am running osx 10.12 on an intel corei7 
I added the print command and the directory I am in is indeed the directory I opened the file from in idle 

/Users/seanwayland/Desktop/jonahmidi

I also tried running this very old mido program from the same directory  I wrote years ago and it works and saves a file : 

```
import mido 
import random
import sys

from mido import Message, MidiFile, MidiTrack

notes = [64, 64+7, 64+12]

with MidiFile() as outfile:
    track = MidiTrack()
    outfile.tracks.append(track)

    track.append(Message('program_change', program=12))

    delta = 16
    for i in range(2):
        
        track.append(Message('note_on', note=notes[i], velocity=100, time=0))
    for i in range(2):
        if i==0:
                    track.append(Message('note_off', note=notes[i], velocity=100, time=delta))
        else:
                    track.append(Message('note_off', note=notes[i], velocity=100, time=0))

    outfile.save('seanstest.mid')

```

**Comment by olemb** [comment]
A, I made a mistake and left the `for msg in mid.play()` in which means it would still play back the file in addition to converting each message for each message. Sorry.

This should work:

```
from mido import Message, MidiFile, MidiTrack
import sys

mid = MidiFile('DarkSoul_110BPM_Gmin_Groove1.mid')
for track in mid.tracks:
   for i, msg in enumerate(track):
        if msg.type == 'control_change':
            ped = msg.value
            pedfix = abs(ped-127)
            # Replace message in track.                                         
            track[i] = msg.copy(value=pedfix)
            print(msg)


#mid.save('new_song.mid')                                                       
```

**Comment by seanwayland** [comment]
eggsellent !! 
It's working !! 
Now I need to figure out how to pass a file as an argument to the program and batch convert a whole folder of midi files .. 
I should be able to figure that out !! 
Thanks so much for your help !!

**Comment by olemb** [comment]
No problem! I'm happy to hear that it works.

I guess I'll just close the issue. Just let me know if you run into more problems.

**Comment by seanwayland** [comment]
thanks again !!
