### ISSUE TITLE
IOError: MThd not found. Probably not a MIDI file

### ISSUE THREAD

**Issue by seanwayland** [olemb/mido#107]
Hi all,
I am having an issue with this mido script which worked a couple of times and then stopped working... I tried a couple of ways of fixing it ( commented code ) like running it with different version of python in different ways ( terminal on OSX or IDLE ) .. 
I tried moving all the midi files into a different folder .. 
It's supposed to batch through a folder of midi files and reverse the polarity of the midi pedal messages .. 
Thanks for your help! 

Here is the error : 

    mid = MidiFile(filename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mido/midifiles/midifiles.py", line 302, in __init__
    self._load(file)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mido/midifiles/midifiles.py", line 326, in _load
    self.ticks_per_beat) = read_file_header(infile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mido/midifiles/midifiles.py", line 110, in read_file_header
    raise IOError('MThd not found. Probably not a MIDI file')
IOError: MThd not found. Probably not a MIDI file

Here is my script 

```
import mido
import os 
from mido import Message, MidiFile, MidiTrack
import sys

def process(filename):
    #mid = mido.read_syx_file(filename)
    mid = MidiFile(filename)
    for track in mid.tracks:
       for i, msg in enumerate(track):
            if msg.type == 'control_change':
                ped = msg.value
                pedfix = abs(ped-127)
                # Replace message in track.                                         
                track[i] = msg.copy(value=pedfix)

    mid.save('*' + filename)


for f in os.listdir('.'):
    # for f in os.listdir('./midifiles'):
    process(f)
```

**Comment by cjappl** [comment]
Can you post the file that's causing the error?

**Comment by seanwayland** [comment]
[jonahmidiissue.zip](https://github.com/olemb/mido/files/1213467/jonahmidiissue.zip)

**Comment by seanwayland** [comment]
That zipped folder has the python program and a couple of midi files in it. 
I have tried lots of different midi files ...

**Comment by olemb** [comment]
I added a `print(f)` to see which file is causing problems:

```
for f in os.listdir('.'):
    print(f)
    process(f)
```

It reads the two `.mid` files fine but then it crashes when it tries to read `jonahmidi.py`.

**Comment by olemb** [comment]
If you have this problem with other files look at the first 4 bytes of the file. A MIDI file should start with the string `"MThd"`. For example, here's a hex dump one of the files you included:

```
00000000: 696d 706f 7274 206d 6964 6f0a 696d 706f  import mido.impo
00000010: 7274 206f 7320 0a66 726f 6d20 6d69 646f  rt os .from mido
00000020: 2069 6d70 6f72 7420 4d65 7373 6167 652c   import Message,
```

If the file starts with `"RIFF...RMID"` you have a RIFF MIDI file:

```
00000000: 5249 4646 044e 0100 524d 4944 6461 7461  RIFF.N..RMIDdata
00000010: f74d 0100 4d54 6864 0000 0006 0001 000b  .M..MThd........
00000020: 01e0 4d54 726b 0000 0019 00ff 5103 03d0  ..MTrk......Q...
```

These are not supported by Mido yet: 
https://github.com/olemb/mido/issues/43

**Comment by seanwayland** [comment]
Thanks very much Martin,
I solved the problem with this 
```
import mido
import os 
from mido import Message, MidiFile, MidiTrack
import sys
def process(filename):
    #mid = mido.read_syx_file(filename)
    mid = MidiFile(filename)
    for track in mid.tracks:
       for i, msg in enumerate(track):
            if msg.type == 'control_change':
                ped = msg.value
                pedfix = abs(ped-127)
                # Replace message in track.                                         
                track[i] = msg.copy(value=pedfix)
 mid.save('*' + filename)
for f in os.listdir('.'):
    if f.endswith(".mid"):
        process(f)
    else:
        print(f)
```

**Comment by olemb** [comment]
Great. I guess I'll close the issue then.

(@cjappl Thanks for helping out, Chris!)

**Comment by seanwayland** [comment]
Thanks again for you help and debugging 101 lesson

On Aug 11, 2017 11:50 AM, "Ole Martin Bjørndalen" <notifications@github.com>
wrote:

Great. I guess I'll close the issue then.

(@cjappl <https://github.com/cjappl> Thanks for helping out, Chris!)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/olemb/mido/issues/107#issuecomment-321849773>, or mute
the thread
