### ISSUE TITLE
about message.channel

### ISSUE THREAD

**Issue by carlitoselmago** [olemb/mido#121]
I'm developing a midi player wich filters a specific track and sends it to a wav sampler.

I'm using MidiFile.play() (with meta_messages=True)

I'm working with karaoke files with .kar extension that include non-standrd messages to hold the lyrics and other info.

I'm having problems to identify the number of the track when parsing each note.

Does the attribute "with meta_messages=True" make the function play() include the non-standard tracks in the track index?

in some songs i'm using, the channel ID doesn't match at all the track I'm targetting.

am I maybe confusing tracks with MIDI channels? if yes, is there a way to know wich track is the message targeting when using MidiFile.play()

**Comment by olemb** [comment]
There's no way to know which track a message comes from with `MidiFile.play()`. To keep things simple the current implementation merges all tracks before it starts playback so this information is lost. If you need to know the track number for each message you will need to write a custom playback function.

Though if all you need is to mute certain tracks a quick and dirty way would be to delete those tracks from the track list before calling `play()`:

```
    mid = MidiFile('test.mid')
    del mid.tracks[0]
    for msg in mid.play():
        out.send(msg)
```

The `channel` attribute is used to target specific MIDI devices. A device can choose to listen to certain channels and ignore others. Any channel can be used on any track so looking at these will not be helpful unless a certain channel is always used for vocals, for example. It doesn't sound like this is the case.

By default `MidiFile.play()` will only return normal MIDI messages (ones that are sent to MIDI devices). Passing `meta_messages=True` will include messages like `set_tempo` and `track_name` that are only found in MIDI files.

**Comment by carlitoselmago** [comment]
Thank you very much for the explination, it was driving me insane.

I guess a dirty quick fix would also be to preparse all tracks and modify
channels of all messages and leave the messages i want to send to the
sampler on an exclusive channel. Since i want to get a perfect synch on the
playback

**Comment by olemb** [comment]
That sounds like it would work.

Do you have any further questions or should I close this issue?

**Comment by olemb** [comment]
Great!
