### ISSUE TITLE
Adding tox/dev dependencies

### ISSUE THREAD

**Issue by cjappl** [olemb/mido#122]
I had an idea (2 linked ideas, actually) that I think would improve the project. 

1. Adding tox to test in both py2 and py3.

I'm not sure if you're aware or familiar with [tox](http://tox.readthedocs.io/en/latest/index.html) but it's great. It creates a new environment for each version of python, installs the dependencies and runs. It's like a more official version of the "run_tests.py" I see in the project right now.

The beauty of it is, all you have to do is type "tox" to run your tests in all your environments. Really has saved my butt before. It can also be configured to check the PEP8 compliance of the code as well. We could make it a requirement to run the tox tests before submitting, so we ensure the code stays clean and all tests are passing.

2. Adding developer only dependencies.

This was an idea I found [here](https://stackoverflow.com/a/28842733/7299836). We could put the dev dependencies (pytest, flake8, etc..) in the dev section of the setup.py so devs could run:

`pip install -e .[dev]`

and get all these extras.

I'd be happy to take this on if it seems worthwhile.

**Comment by olemb** [comment]
I like both ideas. Could you set it up and send me a pull request?

1. `run_tests.py` was always a bit of a hack and a while back I switched to running `pytest2 && pytest3` instead. Tox is a much better solution.

I created an ini file and ran a quick test but I ran into a problem. I'd like to test Mido on Python 3.2 but I only have 3.5 installed. Do you know if there's a way to have it install the version I specify? I had to switch to `envlist=py35,py27` but this would fail on a system with Python 3.6.

(I actually haven't run the tests with 3.2 for a while. It would be good to know if it still works.)

2. You have a go from me on the extra dev dependencies. (Maybe we could have extra dependencies for ports as well that install `python-rtmidi`?)

As for automatic flake8 it caused a problem when it removed an import that was required in another module:  bdc924960160e2677dd196953d622c89b58cbc5d  Do you know a way around this? It would be nice to mark this module as required so flake8 doesn't complain ever time, or maybe there's a cleaner way to write the code that wouldn't trigger it in the first place.

Anyway, great suggestions!

**Comment by cjappl** [comment]
I'd be happy to look into all of this. I'll get back to you.

As for the 2nd point, I'm personally not a fan of automatic PEP8 formatting for that very reason. I like to be notified of the issues so I can fix them if I need to, and omit them otherwise. I feel like we can probably get a good list of rules together so we minimize junk but also prevent false positives.

**Comment by olemb** [comment]
Great!

**Comment by olemb** [comment]
I fully agree with you on PEP8.

**Comment by cjappl** [comment]
See #123

**Comment by olemb** [comment]
I guess we can close this one.
