### ISSUE TITLE
Cleanup test structure

### ISSUE THREAD

**Issue by cjappl** [olemb/mido#126]
I propose we move all of the tests to a top level directory called "test". I believe this is standard practice, and in my opinion, it's nice to have the source separated from the tests.

Proposed structure:

- bin
- docs
- mido
...

- test
    - test_ports.py
    - ...
    - messages
        - test_messages.py
        - ...
    - midifiles
        - test_midifiles.py
        - ...

**Comment by cjappl** [comment]
I'm happy to take this one on, as I'm the one who proposed it. Let me know what you think

**Comment by olemb** [comment]
Great! You have a go from me.

Just one thing, should the directory be called `tests`? That's what I've seen most people use and it makes sense since there's more than one test. (Also `test` looks like it's a temporary directory, but that may just be me).

**Comment by cjappl** [comment]
`tests` works fine for me! I'll get working on it, should hopefully be an easy one.

**Comment by olemb** [comment]
Awesome!

Yeah, should be pretty straight forward.

**Comment by cjappl** [comment]
See #127

**Comment by olemb** [comment]
Guess I can close this.
