### ISSUE TITLE
Start using Travis CI for builds and testing

### ISSUE THREAD

**Issue by cjappl** [olemb/mido#128]
This was actually the idea of @superbock, so credit to him!

I think it'd be nice to integrate Travis CI with this project, so we can be confident that tox is being run and tests are passing before merging. 

From [this tutorial](https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo) it looks like only an admin can do it @olemb. I'm happy to look into it, but I'd need admin privilages (I understand if that's a no-go).

Anyway, I think it'd be something that is nice to have and seems relatively easy to set up.

**Comment by olemb** [comment]
This looks like it's pretty easy to set up. I'll have a go at it.

**Comment by olemb** [comment]
Should be up now, see #129.
