### ISSUE TITLE
Trying to clone one MIDI file to another results in drastically different timing

### ISSUE THREAD

**Issue by drewbharris** [olemb/mido#134]
I'm trying to clone one MIDI file to another (well, more specifically, I'm trying to add tempo information to an existing MIDI file, but first I'm trying to just get the clone working) but when I try to simply write one track's messages to a new file, when I play it, the timing is totally off.

My clone code:

```import time
from mido import MidiFile, MidiTrack, MetaMessage

mid = MidiFile('light.mid')
new_mid = MidiFile()
new_track = MidiTrack()
new_mid.tracks.append(new_track)

for i, track in enumerate(mid.tracks):
    print('Track {}: {}'.format(i, track.name))
    for msg in track:
        print(msg)
        new_track.append(msg)

new_mid.save('new_light.mid')
```

When I play light.mid, I get:

```Drews-MacBook-Pro:~/Documents/Projects/mido drew$ mido-play light.mid
Using output u'IAC Driver Bus 1'.
Playing light.mid.
Song length: 7 minutes, 12 seconds.
```

And when I play new_light.mid, I get:

```Drews-MacBook-Pro:~/Documents/Projects/mido drew$ mido-play new_light.mid
Using output u'IAC Driver Bus 1'.
Playing new_light.mid.
Song length: 1 minutes, 26 seconds.
```

Any ideas? Thanks!
Drew

**Comment by cjappl** [comment]
Can you post the midifile so I can test with it?

**Comment by drewbharris** [comment]
Sure:

[midifiles.zip](https://github.com/olemb/mido/files/1412778/midifiles.zip)

**Comment by drewbharris** [comment]
I'm curious if there's something weird about the midi file - it's a straight export from Ableton Live.

**Comment by cjappl** [comment]
Looking into this a little bit right now. What's the intended BPM of 'light.mid'?

**Comment by cjappl** [comment]
I think that may be the issue. When I look at the ticks_per_beat of mid vs new_mid in your code above I get:

`new_mid.ticks_per_beat == 480`
`mid.ticks_per_beat == 96`

When I changed your code to:

from mido import MidiFile, MidiTrack, MetaMessage

```
mid = MidiFile('light.mid')
new_mid = MidiFile(ticks_per_beat=mid.ticks_per_beat)  #initialize with the right tempo
new_track = MidiTrack()


for i, track in enumerate(mid.tracks):
    print('Track {}: {}'.format(i, track.name))
    for msg in track:
        new_track.append(msg)
        
new_mid.tracks.append(new_track)
new_mid.save('new_light.mid')
mid.save('test_light.mid')


```

It worked! Notice the only change is initializing the new file to the right BPM. You can see [here](http://mido.readthedocs.io/en/latest/midi_files.html?highlight=MidiFile#midi-tempo-vs-bpm) that the default BPM for any midi file is 120, which was off in your case.

**Comment by drewbharris** [comment]
Ah! Thank you! So if I want to take light.mid and change the tempo to 94 BPM, is this the right way to do that:

```
import time
import mido
from mido import MidiFile, MidiTrack, MetaMessage

mid = MidiFile('light.mid')
new_mid = MidiFile(ticks_per_beat=mid.ticks_per_beat)
new_track = MidiTrack()
new_mid.tracks.append(new_track)

new_track.append(MetaMessage('set_tempo', tempo=mido.bpm2tempo(94.0), time=0))

for i, track in enumerate(mid.tracks):
    print('Track {}: {}'.format(i, track.name))
    for msg in track:
        print(msg)
        new_track.append(msg)

new_mid.save('new_light.mid')
```

**Comment by cjappl** [comment]
Any wisdom here @olemb? I've reached the end of my very shallow midi knowledge :)

**Comment by drewbharris** [comment]
Actually, you know, if I load the constructed MIDI file back into my DAW with the audio file, it does seem to line up with the correct tempo. Still getting some kind of drift when I do playback with mido, but I'm going to do a bit more research & testing and report back.

Thanks for your help so far!

**Comment by cjappl** [comment]
Cool! 

Very happy to help, glad you made some progress

Moving to close @olemb 

Feel free to write up more issues as they appear @drewbharris

**Comment by drewbharris** [comment]
Ok, this is verified as working! Thanks a lot!
