### ISSUE TITLE
[Question] How can I grab only the immediate output note_on output?

### ISSUE THREAD

**Issue by 2hands10fingers** [olemb/mido#136]
I'm confused about how to do this. I'm using my MIDI controller to launch websites and bash scripts for fun productivity hacks. https://github.com/2hands10fingers/PythonMidiFun/blob/master/midi-commander.py

As you can see in that link above, I'm launching websites. The problem is that I keep launching 2 of them because of the note_off (I think I dunno). Is there any guidance about how  I can only accept the initial output once?

**Comment by cjappl** [comment]
Yeah, I would guess your initial idea is correct. Midi controllers often send a message when the button is pressed (note on) and one when the button is released (note off).

You can tell what type the notes are using the `type` field of the message you recieve. Something like this should work for checking if the note is a note_off type

`msg.type == 'note_off'`


Also, you can get the midinote without converting the message to a string! It's as easy as

`msg.note`

for note on and off messages.

I recommend checking out the documentation to learn more about the object Mido provides

http://mido.readthedocs.io/en/latest/intro.html#messages

Here's the portion of your code with this all fixed
```
with mido.open_output('MPK mini') as outport:
    for msg in inport:

        if msg.type == 'note_off':
            continue

       midi_note = msg.note

        if midi_note == 64:
            outport.reset()
            webbrowser.open('http://www.reddit.com')
        elif midi_note == 52:
            webbrowser.open('http://www.pitchfork.com')
        elif midi_note == 63:
            webbrowser.open('http://www.netflix.com')
        else:
            print(midi_note)
```

Let me know if this works for you

**Comment by 2hands10fingers** [comment]
Ahhhhh! All is revealed. Thank yo so much. Save for the minor indentation error, it worked like a charm.

**Comment by 2hands10fingers** [comment]
Ahhhhh! All is revealed. Thank yo so much. Save for the minor indentation error, it worked like a charm.

**Comment by 2hands10fingers** [comment]
Actually, hang on. It seems that it continues to launch more of the same website unless I press a a different midi key. This number seems to accumulate over time.

**Comment by 2hands10fingers** [comment]
Actually, hang on. It seems that it continues to launch more of the same website unless I press a a different midi key. This number seems to accumulate over time.

**Comment by cjappl** [comment]
Ah, yeah I see the issue now. Instead of iterating over the messages, why don't you try the `receive` call, as discussed here http://mido.readthedocs.io/en/latest/ports.html#input-ports

This would turn your code into something like:


```
with mido.open_output('MPK mini') as outport:
    while True:
        msg = inport.receive()
	if msg.type == 'note_off':
	    continue

	midi_note = msg.note

        if midi_note == 64:
            outport.reset()
            webbrowser.open('http://www.reddit.com')
        elif midi_note == 52:
            webbrowser.open('http://www.pitchfork.com')
        elif midi_note == 63:
            webbrowser.open('http://www.netflix.com')
        else:
            print(midi_note)
```

**Comment by cjappl** [comment]
What do you think @2hands10fingers ?

**Comment by olemb** [comment]
Just check the message type. When you press a key you will get a `note_on` and when you release it you will get a `note_off`.

```
import mido

with mido.open_input('MPK mini') as inport:
    for msg in inport:
        if msg.type == 'note_on':
            if msg.note == 64:
                webbrowser.open('http://www.reddit.com')
            elif msg.note == 52:
                webbrowser.open('http://www.pitchfork.com')
```

**Comment by cjappl** [comment]
@olemb that's similar to my first answer above, in which he responded:

"Actually, hang on. It seems that it continues to launch more of the same website unless I press a a different midi key. This number seems to accumulate over time."

I thought this would be fixed by using the `receive`function instead, which would block until a note was received, and then each note could be processed individually.

I was thinking that iterating over all of the messages on the inport was causing the repeated launches.

**Comment by olemb** [comment]
Ah, I see.

`for msg in inport:` just calls `receive()` internally so it shouldn't make a difference though. I don't understand what could be causing this.

@2hands10fingers I happen to have the same keyboard (Akai APK mini) and also a mac so I'll run your program and see if I can reproduce the problem.

**Comment by 2hands10fingers** [comment]
@olemb I think the problem might have occurred by running Run Script package within Atom and running the script in Terminal. I haven't experienced the problem since, so I'll close it for now.
