### ISSUE TITLE
Midi loop Delay

### ISSUE THREAD

**Issue by Jimmusic** [olemb/mido#137]
If I want to play a midi file in a loop (say a small drum loop) there is a noticeable delay at the beginning of each cycle
EG
mf = MidiFile('drum.mid')
for i in range(5):
--for msg in mf.play():
----port.send(msg)

Looks like something happens at the first iteration call - sorting all messages.
Is it possible to avoid this delay

Also - Is there a way to change tempo in realtime please

Great Job so far

**Comment by cjappl** [comment]
Could you post the midi file you're having issues with? I'd be happy to look into it for you.

I'm not as sure about the tempo question off the top of my head, that'd be a good question for @olemb.

**Comment by Jimmusic** [comment]
I could but it's every midi file I have tried.  It seems that at the beginning of each enumeration  a merge_tracks is called so there is a delay while it does this before yielding the first message making a midi loop not easy.
From The Midifile class

  def __iter__(self):
        # The tracks of type 2 files are not in sync, so they can
        # not be played back like this.
        if self.type == 2:
            raise TypeError("can't merge tracks in type 2 (asynchronous) file")

        tempo = DEFAULT_TEMPO
        for msg in merge_tracks(self.tracks):
            # Convert message time from absolute time
            # in ticks to relative time in seconds.
            if msg.time > 0:
                delta = tick2second(msg.time, self.ticks_per_beat, tempo)
            else:
                delta = 0

            yield msg.copy(time=delta)

            if msg.type == 'set_tempo':
                tempo = msg.tempo

**Comment by Jimmusic** [comment]
[rock.zip](https://github.com/olemb/mido/files/1451981/rock.zip)
sorry forgot to upload the file and accidentally closed the issue.
I am using a raspberry pi 3 so the delay is  more noticeable than on a fast pc.

Maybe it would be better to merge_tracks just once only on file load.  That would solve my problem but not sure if it would break anything else.

**Comment by Jimmusic** [comment]
Also just noticed that delta has the math performed.  Would it be easy to have an option just to return the delta and let me do my own math to take care of "Real Time" for Time Signature corrections for 6/8 12/8 etc. or should this be a feature request.  I am new to GIT so should I raise a feature request etc

**Comment by olemb** [comment]
Iterating over the file will give you the messages without sleeping:

```
import time
import mido

port = mido.open_output()

mid = mido.MidiFile('rock.mid')
messages = list(mid)

while True:
    for msg in messages:
        time.sleep(msg)
        if not msg.is_meta:
            port.send(msg)
```

If you want to do your own time conversion you can instead do:

```
messages = mido.merge_tracks(mid.tracks)
```

Ideally, the tracks should be merged on the fly as they are played back. I found this to be tricky to implement so I decided to merge them into one track first just to get something working.

**Comment by Jimmusic** [comment]
Thank you very much. Perfect
