### ISSUE TITLE
Sysex data with values over 127 needed for Novation Launch Control XL?

### ISSUE THREAD

**Issue by d-vyd** [olemb/mido#141]
The Novation Launch Control XL [Programmer's Reference](https://global.novationmusic.com/support/downloads/launch-control-xl-programmers-reference-guide)  claims to need sysex data values over 127 in order to set LEDs on the unit.  For example, on pages 6 and 7:

"System Exclusive messages can be used to set the LED values for any button or pot in any
template, regardless of which template is currently selected. This is done using the following
message:

     Hex version F0h 00h 20h 29h 02h 11h 78h Template Index Value F7h
     Dec version 240 0 32 41 2 17 120 Template Index Value 247

Where Template is 00h-07h (0-7) for the 8 user templates, and 08h-0Fh (8-15) for the 8 factory
templates; Index is the index of the button or pot (see below); and Value is the velocity byte that
defines the brightness values of both the red and green LEDs."

I'm trying this code:

     import mido
     port = mido.open_output('Launch Control XL 3')
     msg = mido.Message('sysex', data=[240,0,32,41,2,17,120,1,1,12,247])
     print(msg.hex())
     port.send(msg)

And getting this error:

C:\Python34\python.exe C:/Users/dle/Documents/Programming/Music/Novation_Controller_01.py
Traceback (most recent call last):
  File "C:/Users/dle/Documents/Programming/Music/Novation_Controller_01.py", line 12, in <module>
    msg = mido.Message('sysex', data=[240,0,32,41,2,17,120,1,1,12,247])
  File "C:\Python34\lib\site-packages\mido\messages\messages.py", line 88, in __init__
    check_msgdict(msgdict)
  File "C:\Python34\lib\site-packages\mido\messages\checks.py", line 98, in check_msgdict
    check_value(name, value)
  File "C:\Python34\lib\site-packages\mido\messages\checks.py", line 85, in check_value
    _CHECKS[name](value)
  File "C:\Python34\lib\site-packages\mido\messages\checks.py", line 36, in check_data
    check_data_byte(byte)
  File "C:\Python34\lib\site-packages\mido\messages\checks.py", line 57, in check_data_byte
    raise ValueError('data byte must be in range 0..127')
ValueError: data byte must be in range 0..127

Process finished with exit code 1

Am I reading those instructions from Novation correctly? If so, is it possible to send such a message via mido?

Thank you,
-d. vyd

**Comment by olemb** [comment]
You've included the sysex start and end bytes (0xf0 and 0xf7, or 240 and 247) in the data. If you remove these it should work:

```
msg = mido.Message('sysex', data=[0,32,41,2,17,120,1,1,12])
```

**Comment by d-vyd** [comment]
I tried that previously. But, if you say it *should* work--then I will assume for now that the problem is on my side.  Thank you!

________________________________

**Comment by d-vyd** [comment]
I can now confirm the problem was on my side. Thank you!
________________________________

**Comment by olemb** [comment]
Glad to hear you got it working.
