### ISSUE TITLE
Continually parse incoming messages on specific port

### ISSUE THREAD

**Issue by d-vyd** [olemb/mido#142]
I'm trying to create some added functionality for my Novation Launch Control XL controller. I've already prototyped it using Native Instrument's Reaktor and am now trying to get it working using Python with mido. I understand how to generate MIDI messages but do not understand exactly how the parser works. The examples I've seen show how a fixed number of bits can be turned into a message. Instead, I'd like to continually listen to a port and get the MIDI channel, note, and velocity of incoming notes or the MIDI channel, CC number, and value of incoming CC messages. I'd like to be able to write something like:

while not quit:
     msg = port.parse()
     if msg != None:
          START LONG SERIES OF CHECKS AND RESPONSES HERE

Is something like this possible?

-d. vyd

**Comment by olemb** [comment]
Once you've opened the Launchpad's input port you can use `receive()` or `poll()` to get messages:

```
import mido

# Replace with the actual name of the port.
inport = mido.open_input('Novation Launch Control XL')

while True:
    msg = inport.poll()
    if msg is not None:
        if msg.type == 'control_change':
            print(msg.channel, msg.control, msg.value)

    # ... do other things
```

The port will take care of all of the parsing.

`receive()` waits until a message is available while `poll()` returns `None` if there is no message yet.

You can also iterate over messages in a port.  See https://mido.readthedocs.io/en/latest/ports.html#input-ports

**Comment by d-vyd** [comment]
Excellent. Thank you!

On Dec 13, 2017 3:18 PM, Ole Martin Bjørndalen <notifications@github.com> wrote:

Once you've opened the Launchpad's input port you can use receive() or poll() to get messages:

import mido

# Replace with the actual name of the port.
inport = mido.open_input('Novation Launch Control XL')

while True:
    msg = inport.poll()
    if msg is not None:
        if msg.type == 'control_change':
            print(msg.channel, msg.control, msg.value)

    # ... do other things


The port will take care of all of the parsing.

receive() waits until a message is available while poll() returns None if there is no message yet.

You can also iterate over messages in a port. See https://mido.readthedocs.io/en/latest/ports.html#input-ports

**Comment by olemb** [comment]
Glad I could help! Closing this then.
