### ISSUE TITLE
Exception calling mido.open_output()

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [olemb/mido#145]
Trying to follow the readme's example of playing a file.

Here's my code which mirror's the readme except for changing the filename.
```

port = mido.open_output()
mid = mido.MidiFile(MIDI_SONG)
for msg in mid.play():
    port.send(msg)
```

It generates this lovely mess....
```
Traceback (most recent call last):
  File "X:/Python/MIDI-Video/MidiPlayer.py", line 9, in <module>
    port = mido.open_output()
  File "C:\Python\Anaconda3\lib\site-packages\mido\backends\backend.py", line 111, in open_output
    return self.module.Output(name, **self._add_api(kwargs))
  File "C:\Python\Anaconda3\lib\site-packages\mido\ports.py", line 269, in __init__
    BasePort.__init__(self, name, **kwargs)
  File "C:\Python\Anaconda3\lib\site-packages\mido\ports.py", line 88, in __init__
    self._open(**kwargs)
  File "C:\Python\Anaconda3\lib\site-packages\mido\backends\rtmidi.py", line 186, in _open
    rtapi = _get_api_id(api)
  File "C:\Python\Anaconda3\lib\site-packages\mido\backends\rtmidi.py", line 33, in _get_api_id
    return rtmidi.API_UNSPECIFIED
AttributeError: module 'rtmidi' has no attribute 'API_UNSPECIFIED'
```

I installed rtmidi.

Any clues?

**Comment by olemb** [comment]
Try the `python-rtmidi` package instead.

There are three different RtMidi packages for Python. Mido requires the one called `python-rtmidi`. I'm not familiar with Anaconda but I think it should be available there under the same name.

**Comment by MikeTheWatchGuy** [comment]
That was it!!!

It's Playing my file now!!!

Oh thank you thank you thank you!

**Comment by olemb** [comment]
I'm glad to hear that! :)

**Comment by Hellenab** [comment]
I feel like the dumbest person in the world now -
I have these packages installed through pip3:
`mido`
`python-rtmidi`

I can't run:
`port = mido.open_output()`
Withouth rtmidi

So I also install rtmidi through pip3.
Then I run 
`port = mido.open_output()`

I get:
`AttributeError: module 'rtmidi' has no attribute 'API_UNSPECIFIED'`

How do I tell it to use python-rtmidi instead?
Or do I have to install it through apt? I installed librtmidi-dev and 2v5 but still the same error.

**Comment by olemb** [comment]
I've been playing around with this in a virutalenv and it looks like `rtmidi` and `python-rtmidi` install their files in the same place, which means you will end up using the one you installed last.

The easiest fix is just to uninstall both packages and reinstall `python-rtmidi`:

```
pip uninstall rtmidi
pip uninstall python-rtmidi
pip install python-rtmidi
```

I hope this fixes your problem.

**Comment by JoseMarulanda** [comment]
Hi im sorry if this is a dumb question i am really noob at all of this but im also trying to run
port = mido.open_output()
and i get this  
AttributeError: module 'mido' has no attribute 'open_output'
why is this hapening?
