### ISSUE TITLE
Recipe for Tempo change and volume change?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [olemb/mido#148]
I'm loving `mido`.  Wow, it works so well.

I'm using the loop for my playback

```
        #------- Loop through MIDI file sending commands ------- #
        for i, msg in enumerate(mid.play()):
            if i%5:
                rc = pback.PlayerPlaybackGUIUpdate('Now Playing \n\n{}\n\n              {:0d}:{:02d}'.format(movie_filename,i//60, i%60))
            else:
                rc = PLAYER_COMMAND_NONE

            time.sleep(.25) if  paused else port.send(msg)

```

I want to add tempo and volume adjustments.  What are the calls I need to make.  It wasn't clear to me.

Thanks for your time.

**Comment by cjappl** [comment]
I don't think "volume" is a MIDI parameter. You could change the velocity to the highest possible by changing your last lines to 
```

msg.velocity = 127
time.sleep(.25) if paused else port.send(msg)
```

For tempo adjustments, see the [set_tempo message](http://mido.readthedocs.io/en/latest/meta_message_types.html?highlight=tempo#set-tempo-0x51)

**Comment by MikeTheWatchGuy** [comment]
I did find the tempo page in the docs, but I couldn't figure out exactly how to apply it to my code.  I'm sorry if it's really clear and I'm being a moron.

Thank you for the velocity info.... that totally makes sense and I'll apply a curve to modify velocity rather than a linear reduction now that I understand where and how to do it.  Thank you for that!

**Comment by cjappl** [comment]
Ah, yes it isn't super clear from the docs, maybe we should make an issue for that!

You should send it a MetaMessage of type 'set_tempo'. This would look something like

```
change_tempo_to_188_bpm = MetaMessage('set_tempo', tempo=mido.bpm2tempo(188))
port.send(change_tempo_to_188_bpm)
```

Of course, you need to import MetaMessage and bpm2tempo for this.

**Comment by MikeTheWatchGuy** [comment]
Hmmmm... on the volume suggestion.

`msg `has no attribute `velocity`.

Or does it **sometimes** have an attribute velocity depending on the message?
It only has channel
```
is_meta
is_realtime
program
time
type
```

**Comment by MikeTheWatchGuy** [comment]
I really appreciate the help here!

I see I can get the `ticks_per_beat` from the midi file object.

I want to modify my 'tempo' by a percentage rather than set a specific value.  That means needing to compute Microseconds Per Beat.  
Ticks per second is the value I need to complete the circuit, if my math is right.
The path I'm attempting to go is:->  ticks per second -> beats per second -> microseconds per beat

I'm not seeing, but I'm sure it's here, where to find the values I need. I'm sorry to be back at the well again so soon!

**Comment by MikeTheWatchGuy** [comment]
When I attempt to set the tempo, I'm getting an error

`MidiOutWinMM::sendMessage: message size is greater than 3 bytes (and not sysex)!`

My code is this:
`tempo_msg = mido.MetaMessage('set_tempo', tempo=int(400000))`

I found my song has the default `tempo = 500000`. My code was failing so I hard coded it. Seems like this should work.

**Comment by MikeTheWatchGuy** [comment]
Just read in tiny tiny print,m in the Mido PDF documentation this statement:
   Meta messages can not [sic] be sent on ports.

This explains why I'm getting the errors, but doesn't explain how to change the tempo nor why the example supplied above attempted to send a Meta Message out a port when it's stated as being illegal to do  :-\    (otherwise known as a needless rathole I went down tonight).

**Comment by MikeTheWatchGuy** [comment]
I see now how Tempo could be changed.

Exposing `tempo `in the `MidiFile` object is one potential way I see of implementing tempo in the module as a whole. 

In `play` the time to sleep between messages is computed.  Tempo could be taken into account there.

Does this sound like a reasonable approach?

Something like this:
`    def play(self, meta_messages=False, tempo_scaler=1):`

And then there's a change here:
`            sleep(msg.time/tempo_scaler)`

Seems like this would give new users the capability, keep the old code working as is, and you've added the ability to directly change the tempo to your mido feature list.

**Comment by MikeTheWatchGuy** [comment]
I ended up making a superclass from the MidiFile class
```
class MyMidiFile(mido.MidiFile):
    def __init__(self, **kwargs):
        self.tempo_scalar = 1.0
        super().__init__(**kwargs)
```
This allowed me to create and expose a tempo_scalar attribute that is then used in the `play `method which was included in the superclass as shown on this line of code:
`            sleep(msg.time*self.tempo_scalar)`

Tempo control would be a good feature for the mido team to include in this package, especially since it has no backward compatibility issues and has a low risk as it's only used with the `play `method.

**Comment by MikeTheWatchGuy** [comment]
Closing this one since volume can be implemented in the same location.
