### ISSUE TITLE
Wrong bpm2tempo and tempo2bpm?

### ISSUE THREAD

**Issue by jorgehatccrma** [olemb/mido#21]
The current implementation is 

    def bpm2tempo(bpm):
        """Convert beats per minute to MIDI file tempo.
    
        Returns microseconds per beat as an integer."""
        # 120 => 500000
        # 60 => 1000000
        return int(bpm * (250000.0 / 60))

but this is what I get:

    >>> from mido import bpm2tempo, tempo2bpm
    >>> bpm2tempo(120), bpm2tempo(60)  # should return (500000, 1000000) according to my knowledge and the docstrings!
    (500000, 250000)
    >>> round(tempo2bpm(500000), 1), round(tempo2bpm(1000000), 1)  # should return (120.0, 60.0) according to my knowledge and the docstrings!
    (120.0, 240.0)

I think the implementations should be:

    def bpm2tempo(bpm):
        """Convert beats per minute to MIDI file tempo.
    
        Returns microseconds per beat as an integer."""
        # 120 => 500000
        # 60 => 1000000
        return int(1000000 * 60.0 / bpm)

    def tempo2bpm(tempo):
        """Convert MIDI file tempo to BPM.
    
        Returns BPM as an integer or float."""
        # 500000 => 120
        # 1000000 => 60
        return 1000000 * 60.0 / tempo

**Comment by olemb** [comment]
Fix released in 1.1.13.
