### ISSUE TITLE
Segment fault using portmidi with callback

### ISSUE THREAD

**Issue by FrancescoCeruti** [olemb/mido#24]
Sometimes when calling \<backend\>.open_input(\<port_name\>, callback=\<callback\>), excluding the first time, the application crash with segment-fault.

The strange fact is, without the callback all works fine, and when looking/debugging the code the problem seems located in portimidi.Input._check_error, that sometimes raise an OSError (bad pointer).

I've used this code to spot the problem, the segment-fault occur between "START 2" and "END" prints

```python
import mido

backend = mido.Backend('mido.backends.portmidi', load=True)
port = backend.open_input()

def change_port(backend, port):
    port.close()
    return backend.open_input(backend.get_input_names()[0])

def change_port_callback(backend, port):
    port.close()
    return backend.open_input(backend.get_input_names()[0],
	                          callback=lambda *a: None)

print('START 1')
port = change_port(backend, port)
port = change_port(backend, port)
port = change_port(backend, port)
port = change_port(backend, port)
print('START 2')
port = change_port_callback(backend, port) # Here
port = change_port_callback(backend, port) # Or here
port = change_port_callback(backend, port) # Or here
port = change_port_callback(backend, port) # Or here
print('END')
```

**Comment by velolala** [comment]
Is this related to https://github.com/olemb/mido#known-bugs ?
```
PortMidi in Ubuntu is mistakenly compiled in debug mode, which causes it to print out error message instead of returning an error code:

    PortMidi: `Bad pointer'
    type ENTER...PortMidi call failed...

See https://bugs.launchpad.net/ubuntu/+source/portmidi/+bug/890600

This means here is no way for Mido to catch the error and raise an exception.

This regularity occurs in two places: in PortMidi when you close a port that has a callback, and in pygame when you close any port.
```

**Comment by FrancescoCeruti** [comment]
I'm running on ArchLinux and the package doesn't seem compiled in debug mode, here the PKGBUID:
https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/portmidi

Here the raised OSError:
```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/mido/backends/portmidi.py", line 216, in _thread_main
    self._receive()
  File "/usr/lib/python3.4/site-packages/mido/backends/portmidi.py", line 191, in _receive
    _check_error(num_events)
  File "/usr/lib/python3.4/site-packages/mido/backends/portmidi.py", line 35, in _check_error
    raise IOError(pm.lib.Pm_GetErrorText(return_value))
OSError: b"PortMidi: `Bad pointer'"
```

And here something related form "pypm" code (found googling) at https://bitbucket.org/aalex/pyportmidi/src/f84ec7fa21ad7e7adf4b92f19098340896db7faa/pypm.pyx?at=default#cl-234

```python
if err < 0:
    s = Pm_GetErrorText(err)
    # Something's amiss here - if we try to throw an Exception
    # here, we crash.
    if not err == -10000:
        raise Exception,s
    else:
        print "Unable to open Midi OutputDevice=",OutputDevice," err=",s
```

**Comment by FrancescoCeruti** [comment]
I think I've discovered the problem.

In PortCommon._close() we call pm_Close(self._stream), and while the pm_Close() function free the midi reference (line 00879 http://portmedia.sourceforge.net/portmidi/doxygen/portmidi_8c-source.html),
the callback _thread loop could call Input._receive(), and in this we call Pm_Poll(self._stream), (line 00393), actually the function checks if the passed object is NULL, but for some reason (i'm not a ctype expert), the self._stream is not a NULL object:

form https://docs.python.org/3/library/ctypes.html
```
NULL pointers have a False boolean value
```
but running the following in portmidi.Input._receive()
```python
print(self._stream, '->', bool(self._stream))
```
we get this
```
c_void_p(<somebignumber>) -> True
```

And here we get the segment-fault.
The "bug" can be solved using a lock (in _close() and _thread_main()) and checking the callback before the _receive() function, like this:

```python
def _thread_main(self):
    [...]
    try:
        while self.callback and self._lock.acquire(False):
            self._receive()
            for message in self._parser:
                if self.callback:
                    self.callback(message)
            self._lock.release()
            sleep()
```

Or doing something like this in PortCommon (not tested):

```python
    # And adding a lock
    def _close(self):
        _check_error(pm.lib.Pm_Close(self._stream))
        self._stream = None   # ctype take this as a NULL
        _state['port_count'] -= 1
```

But maybe there' s some way to ensure that the self._stream become a null reference when freed in pm_Close().

**Comment by olemb** [comment]
Ouch. I should have seen this when I wrote the code.

Anyway, I've added some syncronization now. I decided to got with an event instead of a lock as this makes the intention a little bit clearer. You can find the new version in my develop branch.

Here's the test program I used to reproduce the segfault:

    import mido
    
    i = 0
        while True:
        print(i)
        port = mido.open_input(callback=lambda message: None)
        port.close()
        i += 1

It now runs without any problems. Let me know how things are on your end.

Thanks for reporting this!

**Comment by FrancescoCeruti** [comment]
Now works perfectly.

Thanks again for this great project!
