### ISSUE TITLE
Setting callback after initialization does not work when kwarg was not set

### ISSUE THREAD

**Issue by nils-werner** [olemb/mido#25]
The following example does not work:

    def print_message(message):
        print(message)

    port = mido.open_input('Launchpad Mini')
    port.callback = print_message

setting `callback` to anything besides `None` and substituting the callback afterwards, fixes the problem

    def print_message(message):
        print(message)

    port = mido.open_input('Launchpad Mini', callback=lambda x: x)
    port.callback = print_message

even using

    port = mido.open_input('Launchpad Mini', callback=1)

while technically incorrect, fixes the problem.

**Comment by olemb** [comment]
You're right. That's the way it should work.

I've rewritten the callback system in the RtMidi and PortMidi backends to make this possible. You can now set and clear the callback at any time and the callback thread will start and stop as needed. (In RtMidi it just calls set_callback() and clear_callback().)

The changes are available in my develop branch.

Thanks for reporting this!
