### ISSUE TITLE
Bug in merge_tracks (with simple fix)

### ISSUE THREAD

**Issue by CharlesGillingham** [olemb/mido#28]
There's a bug in "merge tracks" ... the relative times should restart on each track. Trivial to fix.

def merge_tracksFIXED(tracks):
    """Returns a MidiTrack object with all messages from all tracks.
    The messages are returned in playback order with delta times
    as if they were all in one track.
    """
    now = 0 #TODO: REMOVE THIS
    messages = MidiTrack()
    for track in tracks:
        now = 0 #TODO: ADD THIS
        for message in track:
            now += message.time
            if message.type not in ('track_name', 'end_of_track'):
                messages.append(message.copy(time=now))
            if message.type == 'end_of_track':
                break

    messages.sort(key=lambda x: x.time)
    messages.append(MetaMessage('end_of_track', time=now))

    # Convert absolute time back to delta time.
    last_time = 0
    for message in messages:
        message.time -= last_time
        last_time += message.time

    return messages

**Comment by olemb** [comment]
Thank you!

I had to make some changes to account for empty tracks and end of track messages, but I've committed a bug fix to my develop branch based on your changes. I will release a new version soon.

This was a pretty bad bug which completely broke MIDI file playback, so I really appreciate you reporting it!

**Comment by olemb** [comment]
I've release a new version (1.1.14).
