### ISSUE TITLE
client name?

### ISSUE THREAD

**Issue by stuaxo** [olemb/mido#33]
If I do `aplaymidi -l` it lists a "client name" is there any way to get this info from mido ?

```
aplaymidi -l
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
 20:0    APC MINI                         APC MINI MIDI 1
128:0    TiMidity                         TiMidity port 0
128:1    TiMidity                         TiMidity port 1
128:2    TiMidity                         TiMidity port 2
128:3    TiMidity                         TiMidity port 3
```

output from get_ioport_names

``` python
>>> mido.get_ioport_names()
[u'APC MINI MIDI 1', u'Midi Through Port-0']
```

**Comment by olemb** [comment]
There is currently no way to get this information from Mido.

Mido uses RtMidi or PortMidi as a backend and as far as I can tell from the
documentation and source code they don't provide client names through their
API so there's no way for Mido to access them.

In RtMidi you can pass a clientName to the RtMidiIn / RtMidiOut contructor,
but it is only used when creating new virtual ports and it doesn't affect
listing of ports.

**Comment by stuaxo** [comment]
The RtMidi guy is proposing an API for this, if it looks good can you let him know ?

https://github.com/thestk/rtmidi/issues/54#issuecomment-154059252

**Comment by olemb** [comment]
Will do.

**Comment by stuaxo** [comment]
Awesome, cheers :)

**Comment by olemb** [comment]
Sounds good.

I've had a look at the code and this will be very easy to add to Mido once
it's supported in RtMidi and python-rtmidi.

**Comment by olemb** [comment]
I've added support for client names in my develop branch. You can specify client name when you open a port:

```
import mido
port = mido.open_output(client_name='My client')
```

This requires python-rtmidi >= 1.0.0rc1.

As for port names it seems that RtMidi uses a prefix:

```
mido.get_input_names()
['Midi Through:Midi Through Port-0 14:0', 'My client:RtMidi output 128:0']
```

I could split these up in Mido but I'm not sure I want to mess with it.

**Comment by olemb** [comment]
Hmm, the ``open_output()`` above seems to have opened a virtual port. I'm not sure what's going on here.

**Comment by olemb** [comment]
OK, it seems if you set a client name in rtmidi it will open make the port a virtual port. This makes sense. I've changed Mido to behave the same way and documented it.

**Comment by cjappl** [comment]
Moving to close
