### ISSUE TITLE
Documentation Error 1.1.14

### ISSUE THREAD

**Issue by twcook** [olemb/mido#41]
The docs say:

**MIDI Files**
MidiFile objects can be used to read, write and play back MIDI files. (Writing is not yet implemented.)

But i reality writing files seems to work okay using the example.

**Comment by olemb** [comment]
Thanks for reporting this!

This was already fixed a while back in the develop branch but there hasn't
been a release for a while so readthedocs is not up to date. I'll hope to
get a new release out soon.
