### ISSUE TITLE
Index Error when trying to open a valid midi file

### ISSUE THREAD

**Issue by Gilthans** [olemb/mido#42]
I attempted to open the attached file using mido.MidiFile, and got an IndexError.
The midi seems valid because winamp plays it without issue, but when I try to load it with mido I get an IndexError in one of the internal decode functions.

(BTW - what a great library!)

[daughter.zip](https://github.com/olemb/mido/files/242237/daughter.zip)

**Comment by olemb** [comment]
I'm glad you like Mido!

From what I can see one of the meta messages is marked with the wrong size. I'll have to look into this a bit more. (If there is an actual error in the file I'm not sure how it should be handled.)

**Comment by olemb** [comment]
I've had a closer look at the file.

The last 3 bytes are:

    ff  (meta message)
    00  (meta message type: sequence_number)
    00  (length (should be 2))

This looks like some kind of end of file or end of track marker.

By the way, thanks for the reports and for attaching the files. It helps out a lot!

**Comment by Gilthans** [comment]
I'm glad they were helpful!

It does seem like some proprietary marker. I'm not sure how things like winamp handle these message. I've check VLC Player (which is open source), and it failed playing the file.
I can't think of any other open source media players which might have a solution for this...

**Comment by olemb** [comment]
@hyst329 found a fix for this problem. I have tested with your file and Mido now reads it without any problems.

I've pushed the changes to my master branch and will include it in the next release.

**Comment by olemb** [comment]
I've released 1.2.6 which fixes this problem so I'm closing the issue.
