### ISSUE TITLE
MIDI to array problem

### ISSUE THREAD

**Issue by AnastasiaDunbar** [olemb/mido#47]
How do you get the length of a melody same as `endtime` including the rest to avoid broken looping for interval mode? `myMidi.length` won't do it.
Here's my code for MIDI to array conversion:
````python
import mido
filename = 'yourMidi.mid'
t = ['note_off','note_on']
velocity = False
interval = True
time = 0
stack = []
print('//[note'+(',vel'if velocity else'')+',start,end]')
array_name = "melody"
s = 'var '+array_name+'=['
endtime = 0
myMidi = mido.MidiFile(filename)
midiStack = [myMidi.tracks[1][1]]
for i, track in enumerate(myMidi.tracks):
    for message in track[2:][:-1]:
        midiStack.append(message)
if interval:
    for message in midiStack:
        time += message.time
        if(not t.index(message.type)):
            endtime = max(endtime,time)
    time = 0
    for message in midiStack:
        time += message.time
        if(t.index(message.type)): #Note on
            stack.append('['+str(message.note)+(','+str(message.velocity)if velocity else'')+','+str(time/float(endtime))+',')
        else: #Note off
            s += stack.pop(0)+str(time/float(endtime))+'],'
    print(s[:-1]+'];')
else:
    for message in midiStack:
        time += message.time
        if(t.index(message.type)): #Note on
            stack.append('['+str(message.note)+(','+str(message.velocity)if velocity else'')+','+str(time)+',')
        else: #Note off
            s += stack.pop(0)+str(time)+'],'
            endtime = max(endtime,time)
    print(s[:-1]+'];')
    print('var melodyduration='+str(endtime)+';')
````

**Comment by olemb** [comment]
I'm not sure what you mean by `endtime`. `track.length

**Comment by olemb** [comment]
Sorry, accidentally sent the message before I had finished writing it. I'll send a full reply in a bit. :)

**Comment by olemb** [comment]
Hi, thanks for writing.

I'm having some trouble understanding what your code does. (I think I'm missing some context.) Could you explain what you want to do and what end time means in this case? That will make it easier for me to help you.

**Comment by AnastasiaDunbar** [comment]
An example of an output from the code would be like:
```Javascript
//[note,start,end]
var melody=[[60,96,144],[60,192,336],[58,336,384],[60,384,480],[56,480,576],[60,576,672],[61,672,768],[60,864,912],[63,960,1056],[60,1056,1104],[58,1104,1152],[60,1152,1248],[56,1248,1344],[60,1344,1440],[68,1440,1536]];
var melodyduration=1536;
```
Look into [TinyRave](http://tinyrave.com/) and you'll understand a bit more why.
But I realized by now. Does and only 384 notes fit in a beat?
Because as I said before:
>  How do you get the length of a melody same as endtime **including the rest** to avoid broken looping for interval mode? 

![hint](https://cloud.githubusercontent.com/assets/11806048/16088056/aa0df29c-3325-11e6-88b6-f6368bb5fcee.png)


I think the solution is: `endtime = floor(endtime/384)*384`.
But how do I get integer length of a midi? `myMidi.length` would give me a float and not the same as `endtime`'s value.

![hint](https://cloud.githubusercontent.com/assets/11806048/16088105/dc77b664-3325-11e6-85db-e132a813ea30.png)

I have to loop for each note just to get the length of the midi.

**Comment by olemb** [comment]
Sorry I've taken so long to reply. I hope you have solved your problem in
the meantime.

The problem here is that there are two different units. `myMidi.length`
gives you the length of the song in seconds so this won't work for you.

The `time` attribute on the messages on the other hand are in ticks. The
only way to get the end time in ticks is to go through all messages and add
up the times as you've done.

I've written a bit about time units here:


https://mido.readthedocs.io/en/latest/midi_files.html#tempo-and-beat-resolution

One other thing to keep in mind is that the last note off may not be the
last message in the file. The last message is typically an 'end_of_track'
message. This allows you to have some silence after the last note. If you
only look at the last note off you may miss this silence, which means loop
will be too short.

**Comment by AnastasiaDunbar** [comment]
So how do I correctly get a note's length without using stacks?

**Comment by olemb** [comment]
I think I'd put the `'note_on'` messages in a dictionary (with note as key). Then when I got a `'note_off'` I could look it up in the dictionary to get the start and end time of the note.

This is a lot easier if you convert to messages times to absolute time. You could use something like this:

```
def to_absolute_time(track):
    messages = []
    now = 0
    for msg in track:
        messages.append(msg.copy(time=now+msg.time))
        now += msg.time

    return messages
```

```
>>> from mido import Message
>>> print(to_absolute_time([Message('note_on', time=1), Message('note_off', time=2)]))
>>> [<message note_on channel=0 note=0 velocity=64 time=1>, <message note_off channel=0 note=0 velocity=64 time=3>]
````

and then do:

```
for msg in to_absolute_time(track):
    # insert and look up notes as described above
```

**Comment by AnastasiaDunbar** [comment]
That's better. Thanks for the tip, but will there be no problems if there are notes overlapping?

```Python
import mido
import math
filename = 'yourMidi.mid'
velocity = False #Put velocity in array
interval = False #0 to 1
endAtBar = True  #Set melody duration to end of bar
arrayName = "melody"
durationName = "melodyduration"
def toAbsoluteTime(track):
    messages = []
    now = 0
    for msg in track:
        messages.append(msg.copy(time=now+msg.time))
        now += msg.time
    return messages
t = ['note_off','note_on']
print('//[note'+(',vel'if velocity else'')+',start,end]') #Tip
arrayString = 'var '+arrayName+'=['
myMidi = mido.MidiFile(filename)
midiStack = toAbsoluteTime(myMidi.tracks[1])[1:][:-1]
endtime = midiStack[-1].time #Length of MIDI
if endAtBar:
    endtime=math.ceil(endtime/384.)*384
stack = {}
if interval: #0 to 1
    for message in midiStack:
        key = str(message.note)
        if not key in stack:
            stack[key]=[]
        if(t.index(message.type)): #Note on
            stack[key].append('['+str(message.note)+(','+str(message.velocity)if velocity else'')+','+str(message.time/float(endtime))+',')
        else: #Note off
            arrayString += stack[key].pop(0)+str(time/float(endtime))+'],'
    print(arrayString[:-1]+'];')
else: #Not interval
    for message in midiStack:
        key = str(message.note)
        if not key in stack:
            stack[key]=[]
        if(t.index(message.type)): #Note on
            stack[key].append('['+str(message.note)+(','+str(message.velocity)if velocity else'')+','+str(message.time)+',')
        else: #Note off
            arrayString += stack[key].pop(0)+str(message.time)+'],'
    print(arrayString[:-1]+'];')
    print('var '+durationName+'='+str(endtime)+';')
```

**Comment by olemb** [comment]
It should work fine as long as they don't have the same the same note
number.

**Comment by AnastasiaDunbar** [comment]
If there's a way to fix that, I would like to know.

**Comment by olemb** [comment]
Unfortunately I can't see a way around this.

Let's say you have two 'note_on' messages with the same note number:

    note_on note=60 time=10
    note_on note=60 time=20

Then this 'note_off' comes along:

    note_off note=60 time=30

but is it the end of the first or the second note?

**Comment by AnastasiaDunbar** [comment]
I wish I knew how professional programs read MIDI files.

**Comment by olemb** [comment]
Same here.

There are some open source programs you can study though. The one that
comes to mind is Rosegarden.

**Comment by olemb** [comment]
Closing this. Feel free to comment if you have further questions.
