### ISSUE TITLE
[enhancement]  add support for rtmidi-python

### ISSUE THREAD

**Issue by netchose** [olemb/mido#55]
hi,

if you cann add support for rtmidi-python https://github.com/superquadratic/rtmidi-python

this library is very simple to install on windows with precompiled wheel 👍 http://www.lfd.uci.edu/~gohlke/pythonlibs/#rtmidi-python

i'm on windows 64bit and it's the only midi library i can use

thanks a lot

**Comment by olemb** [comment]
I started writing a backend for rtmidi-python a while back but I never
finished it.

It should not be hard to do since there's already a very similar backend
for python-rtmidi. I have a lot going on now but I will see what I can do.

Let me know if you want to have a go at it. :)

**Comment by olemb** [comment]
I've written a backend for rtmidi-python: https://github.com/olemb/mido/blob/develop/examples/backends/rtmidi_python_backend.py

For now it's in the examples folder but I may add it to the package at some point.

Let me know if you have any problems.
