### ISSUE TITLE
Opening the same device for input and output?

### ISSUE THREAD

**Issue by lukeoftheaura** [olemb/mido#57]
Pardon my ignorance if this is in the docs but I can't find it, is it possible to open the same device for both input and output?

**Comment by olemb** [comment]
Yes, the easiest way is to do:

    port = open_ioport(name)

This will give you a port you can use to both input and output.

Alternatively, you can open the input and output separately:

    inport = open_input(port_name)
    outport = open_output(port_name)

`open_ioport()` is just a shortcut for this that also wraps the ports in a
convenient IOPort object so you don't need two objects to talk to one
device.

**Comment by cjappl** [comment]
This issue can probably be closed!

**Comment by lukeoftheaura** [comment]
closing issue
