### ISSUE TITLE
Errors in MacOS 10.12

### ISSUE THREAD

**Issue by talbaumel** [olemb/mido#58]
Hi, getting: 'OSError: dlopen(libportmidi.dylib, 6): image not found'
When trying to execute: 'mido.get_input_names()'

Thanks, great library! (regardless of the error)

**Comment by olemb** [comment]
Hi,

I'm glad you're enjoying Mido!

To use ports you need either PortMidi or RtMidi installed on your system. The error message means that Mido can't find the PortMidi library.

If you have Homebrew you can install it with:

    brew install portmidi

I would recommend RtMidi though. You can install it with:

    pip install --pre python-rtmidi

but you will need to either use `mido.set_backend()` or set the `$MIDO_BACKEND` environment variable to tell Mido to use RtMidi.

You are not the first to run into this problem. You may find some useful information in the discussion on issue #44.

I hope this helps!

**Comment by talbaumel** [comment]
It did THANKS, but I got one more problem

Got it to recognize my MIDI keyboard as input but I can't see the computer speakers as output (I'm on mac) any idea if it is possible?

On a windows machine I can see speakers as "Microsoft GS Wavetable Synth"

**Comment by olemb** [comment]
I'm guessing this is USB audio. Could it be that you need a driver for it?
I have some devices that work fine in Linux but require drivers on the mac
for some reason.

Which keyboard is it?

**Comment by olemb** [comment]
By the way, good to heard it worked out for you! Did you god with PortMidi or RtMidi?

**Comment by talbaumel** [comment]
It worked usinf RtMidi
The keyboard is "Arturia MINILAB" and I'm trying to get the output to play on my laptop speakers

**Comment by olemb** [comment]
Ah, I see what's going on. "Microsoft GS Wavetable Synth" is a software synthesizer that comes with Windows. The mac doesn't have anything like this out of the box so you need to look around for something to install, or use Garage Band if you have that. (Not sure if they still include it.)

**Comment by talbaumel** [comment]
I'm using Logic (Pro X)
Any idea how to set it up?

**Comment by olemb** [comment]
I've never used Logic, but there is typically something under "Preferences"
or "Settings" where you select which keyboard to use. Some programs will
use any keyboard you've plugged in but others, like Reason, need to be told.

Where does Mido come in here though? :)

**Comment by olemb** [comment]
Let me know if you need help connecting Mido up to Logic. (If you open a virtual port you should be able to select it in Logic.)

**Comment by talbaumel** [comment]
Yeah, I opened a virtual port and logic and Mido recognized it
automatically:)

**Comment by olemb** [comment]
Nice. :)
