### ISSUE TITLE
Returning from a function when there's no message

### ISSUE THREAD

**Issue by lukeoftheaura** [olemb/mido#59]
Hi,
I have the following function using your library:

```
def get_input(self):
        for message in self.padinput:
            if message.type == "note_on":
                xy = self.miditoxy(message.note)
                xyv = (message.type, xy[0],xy[1],message.velocity)
                return xyv
            elif message.type == "control_change":
                return (message.type, message.control-104, message.value)
```

How would I add another `if` making the function return something else, immediately, if no input comes from the port?

**Comment by olemb** [comment]
Hi,

If you want to receive one message or do something else if there is no message you can use `receive(block=False)`:

    def get_input(self):
        message = self.padinput.receive(block=False):
        if not message:
            return None

        if message.type == "note_on":
             xy = self.miditoxy(message.note)
             xyv = (message.type, xy[0],xy[1],message.velocity)
             return xyv
        elif message.type == "control_change":
            return (message.type, message.control-104, message.value)
        else:
            # Unknown message type.
            return None

**Comment by kerbingamer376** [comment]
Thanks, that sorted it.

**Comment by olemb** [comment]
Happy to hear that!

I'm closing the issue then.

**Comment by kerbingamer376** [comment]
Now, Half the messages that come in from the device just aren't being detected, whereas if I use the function I originally was using that was blocking, the messages do get detected

**Comment by olemb** [comment]
Strange. Well, I guess the first thing to find out is where message goes missing. Could you add a print after the receive line?

```
message = self.padinput.receive(block=False)
print(message)
```

If all the messages are printed we know the problem is not inside `receive()`.

I rewrote your code a bit. Maybe that did it. Here's another version of your function with only minimal changes:

```
def get_input(self):
		message = self.padinput.receive(block=False)
        	if message:
			if message.type == "note_on":
				xy = self.miditoxy(message.note)
				xyv = (message.type, xy[0],xy[1],message.velocity)
				return xyv
			elif message.type == "control_change":
				return (message.type, message.control-104, message.value)
```

(I think I'll add a `poll()` function to ports so you can write `port.poll()` instead of `port.receive(block=False)`.)

**Comment by cjappl** [comment]
@lukeoftheaura Has @olemb's solution helped you with this? There hasn't been any action for a long time

**Comment by lukeoftheaura** [comment]
yes, that fixed the problem.
