### ISSUE TITLE
Error in creating new MIDI files

### ISSUE THREAD

**Issue by dajaj** [olemb/mido#64]
I got an error when saving a mid file with 
```python
mid.save('myfile.mid')
```

The error is :
***
  File "/usr/lib/python3.5/site-packages/mido/midifiles.py", line 461, in save
    self._save(file)
  File "/usr/lib/python3.5/site-packages/mido/midifiles.py", line 487, in _save
    bytes += encode_variable_int(message.time)
  File "/usr/lib/python3.5/site-packages/mido/midifiles_meta.py", line 104, in encode_variable_int
    raise ValueError('variable int must be a positive integer')
***
I found out that `message.time` coulde be either an int or a float (http://mido.readthedocs.io/en/latest/messages.html#the-time-attribute) and that in `midifiles.py` the float possibility is not checked (l.487).

My MIDI file had indeed float time attributs, that's why it didn't work.

**Comment by olemb** [comment]
While floats are allowed in Mido messages they are not allowed in MIDI files.

Time in MIDI files is given in ticks and they must be integers. I should probably add something about this to the docs.

**Comment by dajaj** [comment]
I work on existing MIDI files (free downloads), and they have floats...

**Comment by olemb** [comment]
That's surprising. Do you have an example I can look at?

**Comment by dajaj** [comment]
Of course :  http://www.midiworld.com/download/3855

**Comment by olemb** [comment]
Thanks.

I tried printing out the times of all messages and I get integers:

```
import mido

mid = mido.MidiFile('/home/olemb/Desktop/Movie_Themes_-_Star_Wars_-_Duel_of_the_Fates.mid')

for track in mid.tracks:
    for msg in track:
        print(msg.time)
```

However, if you loop over the file you will get floats:

```
for msg in mid:
    print(msg.time)
```

but this is because the time values are converted from ticks to seconds.

`for msg in mid:` is a shortcut for `for msg in mid.play(sleep=False)`, which was a bad choice on my part and has caused a lot of confusion.

**Comment by olemb** [comment]
By the way, thanks for the link to midiworld. It's a good resource.

**Comment by dajaj** [comment]
Thank you very much :-) I would never have figured it out on my own.

For now I'll use the correct way to iterate over messages.

Thanks again
