### ISSUE TITLE
PortMidi: `Bad pointer' error when closing port with pygame backend on Windows

### ISSUE THREAD

**Issue by AvivC** [olemb/mido#65]
I'm using `mido` with the `pygame` backend on Windows 7 and Python 2.7.

When running this:

```
import mido
import time

mido.set_backend('mido.backends.pygame')

output = mido.open_output()
output.send(mido.Message('note_on', note=64, velocity=60))
time.sleep(3)
output.close()
```
The following error is printed to stderr in the last line:

```
Exception Exception: "PortMidi: `Bad pointer'" in <pypm.Output object at 0x025FF0B0> ignored
```

This error is mentioned as a known bug, but only under Ubuntu. This happens to me on Windows.

Apart from this everything seems to work, but I'm developing a console app so this is problematic. Is there a way for me to fix this? Or should I just use RtMidi as the backend instead?

Thank you

**Comment by olemb** [comment]
I would recommend RtMidi. PortMidi has a few of these problems that can
only be fixed by recompiling it.

**Comment by AvivC** [comment]
Indeed I've switched to RtMidi and so far it works flawlessly. Thanks :)

**Comment by olemb** [comment]
Happy to hear that. :) Closing the issue then.
