### ISSUE TITLE
IOPort.receive() does not return

### ISSUE THREAD

**Issue by dagargo** [olemb/mido#67]
Around commit [1306d31](https://github.com/olemb/mido/commit/1306d31c51793f30b5936dadbdbbc17dfcac995e), the overwriting of `Input._receive()` was replaced by the overwriting of `Input.receive()` in the rtmidi module.
As there is no custom `IOPort` in rtmidi, the calls to the method `IOPort.receive()` do not work. However, `Input.receive()` works as expected.

This can be fixed in appending this code to the rtmidi module.
```
from mido.ports import IOPort as CommonIOPort

class IOPort(CommonIOPort):

    def __init__(self, name, **kwargs):
        self.input = Input(name, **kwargs)
        self.output = Output(name, **kwargs)
        super(IOPort, self).__init__(self.input, self.output)

    def receive(self, block=True):
        return self.input.receive()
```
But since you are doing some changes to the internal API used by the backends in the mentioned methods I am not sure if adding this is a good idea.

**Comment by olemb** [comment]
In the develop branch it overrides ``_receive()`` again. Could you check if it works there?

I am worried that the lock is messing things up. It was probably a mistake to add locking to the base ports. The RtMidi backend as it is now doesn't require any locking and the locks create all sorts of tricky situations.

**Comment by dagargo** [comment]
It works on the develop branch. Next time, I will try it first.
Thank you so much for your support.
Kind regards.

**Comment by olemb** [comment]
I'm happy to hear that.

I've made some major changes in the develop branch and there's still a lot of testing to be done. Let me know if you run into any problems.

**Comment by olemb** [comment]
Yes, this had to be done because ``_receive()`` couldn't return a message.
In the develop branch I've changed this so I've switched back to overriding
``_receive()``. Does the code in the develop branch work as expected?

**Comment by dagargo** [comment]
Sorry for taking so long to answer but I wanted to check my two applications. Besides, I needed to apply a workaround to prevent the MidiOutAlsa error in the sequencer API. 
However, it looks like the code in the develop branch works all right.

**Comment by olemb** [comment]
Ah, good. Should I just close this issue?

**Comment by dagargo** [comment]
I already closed it many days ago. Maybe I shouldn't have, Sorry.

**Comment by olemb** [comment]
No worries. I forgot that you had already closed the issue and just wanted to make sure that your problem had been solved.
