### ISSUE TITLE
Where is Channel 10?

### ISSUE THREAD

**Issue by jeremyfromearth** [olemb/mido#76]
I recently started using your library to learn more about the MIDI spec in hopes of building music data visualization tools. As I understand it, MIDI channel 10 is reserved for percussion instruments. I've opened multiple MIDI files with mido and have yet to see any activity in channel 10. Am I missing something obvious or does mido not support the percussion channel?

**Comment by olemb** [comment]
Hi Jeremy,

Channels are numbered 0-15 in Mido so everything is one lower. You should be seeing some drum action on channel 9.

**Comment by jeremyfromearth** [comment]
Of course, thanks for your quick reply!
