### ISSUE TITLE
can't find libportmidi.dylib when using MacPorts

### ISSUE THREAD

**Issue by yam655** [olemb/mido#77]
I'm working on an app using mido. I work on a Mac, and I currently prefer to use MacPorts as my secondary package manager of choice. I'm also using Python 3.5 right now.

I'm using virtualenv, as I'm working on my app, so mido itself was a `pip install` to a normal virtualenv-based directory.

I double-checked that libportmidi.dylib was available in my LD_LIBRARY_PATH. It's in /opt/local/lib -- as is normal for a MacPorts install. This is on the LD_LIBRARY_PATH and it should work...

However, I got an error in `portmidi_init.py` that it couldn't be found.

I also found that the issue was easily fixed by changing:

```python
lib = CDLL(dll_name)
```

to the following:

```python
lib = CDLL(find_library(dll_name))
```

**Comment by olemb** [comment]
Thanks for the fix. I have tested it and can confirm that it also works with Homebrew. I've committed it to my 1.1.x branch and will include it in 1.1.19.

For now I've only made the change for ``sys.platform == 'darwin'`` as I ran into some problems using it on Linux. I'll have to look into this.
