### ISSUE TITLE
receive() in IOPort not working

### ISSUE THREAD

**Issue by dagargo** [olemb/mido#83]
Hi!

I'm having some troubles when invoking receive() from a IOPort. Here is what I've tried.

This code never receives anything.
```
#!/usr/bin/env python3
import mido
mido.set_backend('mido.backends.rtmidi')
ports = mido.get_input_names()
p = mido.open_ioport(ports[0])
p.receive()
```
This code works and ends when a note is received.
```
#!/usr/bin/env python3
import mido
mido.set_backend('mido.backends.rtmidi')
ports = mido.get_input_names()
p = mido.open_input(ports[0])
p.receive()
```
Am I doing something wrong?
Thanks in advance.

**Comment by olemb** [comment]
You are not doing anything wrong. This was caused by a bug in `IOPort` which has gone undiscovered since 1.0.3 (August 2013).

I've fixed the bug and released 1.2.1. Thanks for reporting!
