### ISSUE TITLE
python-rtmidi installation instructions are out-of-date

### ISSUE THREAD

**Issue by SpotlightKid** [olemb/mido#87]
The installation instructions for python-rtmidi aren't accurate (any more):

https://github.com/olemb/mido/blob/master/docs/installing.rst#installing

I released [python-rtmidi](https://pypi.python.org/pypi/python-rtmidi) 1.0.0 a while ago. Using `pip install --pre` shouldn't be necessary anymore.

Also, python-rtmidi comes with it's own copy of the RtMidi source code and compiles it statically into the `_rtmidi` extension module. So `librtmidi-dev` shouldn't be a dependency and to my knowledge never was.

**Comment by olemb** [comment]
Ah, they were indeed badly out of date. I've updated them. Thank you!
