### ISSUE TITLE
Question On Sending Midi Messages 

### ISSUE THREAD

**Issue by JoshKir** [olemb/mido#89]
I've been using mido to send messages in real time with keyboard inputs. I am able to hear the notes being played out of my speakers but I am having no luck with external software like Cubase and Midi-OX recognizing the output messages. Here is an example of how I send a message: 
outport.send(mido.Message('note_on', note=60+octave, velocity=80))

Any help is greatly appreciated and sorry for my lack of knowledge on this stuff but I am still rather novice.

**Comment by olemb** [comment]
Hi Josh,

Your code is correct so if you're not hearing anything it could be that
you're sending the message to the wrong port or that Cubase is not set up
correctly to receive it.

What is the name of the port you're sending to? You can find this with:

   print(output)

**Comment by JoshKir** [comment]
I have tried with setting the outport to the built in Windows GS Wavetable Synth, and with a virtual port created by rtpMIDI. When I print the ports it recognizes the virtual ports but I haven't had any luck with the external software reading the messages although they see the ports. Let me know if you would like to see any other parts of my code.

**Comment by olemb** [comment]
I don't know how much help I can be here since I don't know Windows, rtpMIDI or Midi-OX but here's what I've got.

For the built in wavetable synth you should be able to just open its port and send it messages.

For Cubase I think you need to send messages to the rtpMIDI port and then set your the input port of your cubase track to receive from the rtpMIDI port. Also the track needs to be set to channel 1 (or whichever channel your messages are sent on plus one, since Mido starts counting at 0 and Cubase starts at 1).

**Comment by JoshKir** [comment]
I appreciate the help and I hope this isn't too much of a bother. Do you know anyone who has success on Windows? I am begging to think the issue is with the backend being rtmidi; I remember hearing that rtmidi does not support sending midi messages on windows. I understand if there is nothing you can do to help, but if you are able to that would be great.

**Comment by olemb** [comment]
Thanks for your understanding.

Rtmidi should work in Windows but perhaps there are limitations that I'm now aware of. I have heard from people who have used it successfully. (See issue #65 for example.)

I have Windows 8 in a virtual machine, so I intalled the `mido` and `python-rtmidi` packages and wrote this program:

```
import time
import mido
from mido import Message

# mido.set_backend('mido.backends.pygame')

# print(mido.get_output_names())
 
port = mido.open_output('Microsoft GS Wavetable Synth 0')
 
for note in range(60, 80):
    print(note)
    port.send(Message('note_on', note=note))
    time.sleep(0.1)
    port.send(Message('note_off', note=note))
    time.sleep(0.1)
```

The timing is way off due to VirtualBox issues but I do get sound out of it. I wonder what could be different on your system.

As a workaround for now you could switch to the Pygame backend. It's a bit more limited in functionality but should install and work on Windows. If you want to try it out just do:

```
pip install pygame
```

and then add this to the top of your program:

```
import mido
mido.set_backend('mido.backends.pygame')
```

**Comment by JoshKir** [comment]
Thanks for testing on your virtual machine for me, I tried the program and when I run it in my Anaconda Enviroment I still have the same issue but when I made it an exe and tried to run it it said 
"ImportError: No module named 'mido.backends.rtmidi'
Failed to execute script new_test"
Do I not have rtmidi properly installed? When I try to pip install rtmidi I get
"error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2"
I do have python-rtmidi properly installed but I am not sure as to if this is a problem. 
Thanks for the continued help :)

**Comment by JoshKir** [comment]
I also have rtmidi_python installed

**Comment by olemb** [comment]
From the error message ("No module named 'mido.backends.rtmidi'") it looks like you're running a very old version of Mido. From what I can tell the one in Anaconda is 1.1.13 which is over 2 years old. To get the latest one I would recommend "pip install mido".

Somewhat confusingly there are 3 different RtMidi packages for Python:

* `python-rtmidi` is the one Mido uses
* `rtmidi-python` can also be used with Mido by setting the backend to `mido.backends.rtmidi_python`. This one is a little bit more limited.
* `rtmidi` seems to be broken.

So: `pip install python-rtmidi`.

**Comment by olemb** [comment]
Oh, wait. Sorry. You already tried `python-midi` of course.

I guess `rtmidi_python` is the next thing to try then.

**Comment by JoshKir** [comment]
I am still trying to turn my python program into an exe and I am starting to think it might be an issue with pyinstaller finding what modules it needs. However out of curiosity, were you able to have any success with other software recognizing the midi outputs on your virtual machine? Also if you have any experience with creating exe from mido projects, that would be great.

**Comment by olemb** [comment]
This might help: https://mido.readthedocs.io/en/latest/freezing.html

I got sound out of the built-in wavetable synth using the program I posted above but I haven't tried turning it into an exe file. I just ran the program from IDLE.

Which version of Windows are you on? I used Windows 8. I also tried to install on Windows 7 and 10 but ran into another import error when importing `rtmidi`. (It can't find the DLL file. I am looking into it.)

**Comment by olemb** [comment]
I will see if I can find some other programs to test with.

**Comment by JoshKir** [comment]
I added import mido.backends.rtmidi to my code and pyinstaller was able to make it into an exe. I look forward to hearing how your tests with the programs go. Also I am using Windows 7.

**Comment by olemb** [comment]
I installed a demo version of Reason and was able to send it messages through loopMIDI (https://www.tobias-erichsen.de/software/loopmidi.html). All I had to do in Reason was to set up a controller for the loopMidi device. In Cubase you can select device on the track if I remember correctly.

So far I've tested this on Windows 8 and 10 and with Python 2.6.1 and the RtMidi and Pygame backends. I also tried the `rtmidi-python` backend but it doesn't work with Python 3. Good to know.

The Window wavetable synth also works in Windows 8 but for some reason not in Windows 10. I can see it in the port list but when I try to open it I get an exception. This is true for both RtMidi and Pygame so there seems to be something going on deeper down somewhere.

I will try the same on Windows 7.  This time test with PianoTeq: https://www.pianoteq.com/try
It's easier to install and should work with loopMIDI without any configuration.

I'd like to get my configuration as close as possible to yours, so a couple of follow-up questions: Are you on 32-bit or 64-bit Windows, and which version of Python are you using?

**Comment by JoshKir** [comment]
I'm using 64 bit Windows and have been testing with both python 2.7 and 3.4

**Comment by olemb** [comment]
Thanks! I will try this next.

**Comment by JoshKir** [comment]
Thank you!

**Comment by olemb** [comment]
Have you tried loopMIDI? That seems to be the best way to connect things.

**Comment by JoshKir** [comment]
Just tried loopMIDI and the ports work perfectly! I guess the whole time the problem was with the ports I was creating and not code related. Looks like everything is working flawlessly now! Thank you so much for your help and hope this wasn't too much of a bother.

**Comment by olemb** [comment]
That's great news! I hope you'll enjoy Mido.

No bother at all. It was good to get some experience with Mido in Windows.
