### ISSUE TITLE
rtmidi backend with JACK fails to open outputs

### ISSUE THREAD

**Issue by shabble** [olemb/mido#90]
when using python 3.5 / mido 1.2.4 from ipython shell, attempting to open a JACK-backed output port fails with `OSError: unknown port 'jack_mixer:midi in'`. Opening alsa (or default with no args given) ports does succeed.

Jack is configured with 'alsa seq' midi backend, and `import rtmidi; rtmidi.get_compiled_api()` returns `[2,3]`, corresponding to both ALSA and JACK API support.

STR:

* `$ export MIDO_BACKEND=mido.backends.rtmidi/UNIX_JACK` (per docs)
* `$ ipython`
* `> import mido; print(mido.backend); print(mido.get_output_names()); mido.open_output('jack_mixer:midi in')`

gives:

```
<backend mido.backends.rtmidi/UNIX_JACK (loaded)>
['jack_mixer:midi in', 'midi-monitor:input', 'system:midi_playback_1']
OSError: unknown port 'jack_mixer:midi in'
```

A bit of poking suggests that in `backends/rtmidi.py:Output._open`, the initial `rtmidi.MidiOut` call needs the appropriate `rtapi=` kwarg similar to how get_devices does.

A trivial patch which (I think) solves my problem here is:

```
--- rtmidi.py	2017-04-26 21:25:35.976253379 +0100
+++ rtmidi.py.mine	2017-04-26 21:25:03.787777692 +0100
@@ -222,7 +222,8 @@
         self.closed = True
         self._send_lock = threading.RLock()

-        self._rt = rtmidi.MidiOut(name=client_name)
+        rtapi = _get_api_id(api)
+        self._rt = rtmidi.MidiOut(name=client_name, rtapi=rtapi)

         self.api = _api_to_name[self._rt.get_current_api()]
         self._device_type = 'RtMidi/{}'.format(self.api)
```

but not sure if this is the right way to go about it, and there are probably other places (like Input) that'll need similar.

If this looks plausible, I can submit a merge request if desired?

**Comment by olemb** [comment]
I accidentally left this out when I refactored the RtMidi backend for Mido 1.2. Sorry.

The same line is missing from the Output class as well.

If you send me a pull request I'll merge it and put out a new version.

**Comment by olemb** [comment]
Thank you. The new version is out (1.2.5).

**Comment by phil123456** [comment]
anyone can help me out ?
I set the jack backend (jack is running)

no ports can be found

>>> import mido
>>> mido.set_backend('mido.backends.rtmidi/UNIX_JACK')
>>> mido.get_output_names()
[]
