### ISSUE TITLE
Way to connect two mido ports?

### ISSUE THREAD

**Issue by cjappl** [olemb/mido#98]
Hi,

Wondering if there is a way to connect two virtual mido ports. This would be used in a unit test.

What I've tried is:
`   
    def test_send(self):
        NOTE = 127

        msg = mido.Message('note_on', note=NOTE)

        with mido.open_output('send port', virtual=True) as snd:
            with mido.open_input('recv port', virtual=True) as rec:
                snd.send(msg)
                assert rec.poll()

`

The assert always fails because the rec is returning None (isn't receiving a message).

Apologies if I missed something obvious here! Great library, thanks for your time.

**Comment by cjappl** [comment]
Using RtMidi backend, if that makes any difference

**Comment by olemb** [comment]
I'm glad you like Mido!

Thanks for the clarification. What's happening here is that you're opening two virtual ports (ports for other programs to connect to) but since there is no connection between the two the message is lost.

The test passed when I changed it to:

```
    msg = mido.Message('note_on', note=NOTE)

    with mido.open_output('send port', virtual=True) as snd:
        with mido.open_input('send port') as rec:
            snd.send(msg)
            assert rec.receive()
```

but that's probably not what your after. What are you testing for? Maybe I can help you rewrite the test.

**Comment by cjappl** [comment]
Ah, interesting! Do the ports names have to match? AKA if I do:

`mido.open_output('send port', virtual=True)`

Then

`mido.open_input('send port')`

Is saying "Connect me to the port called "send port" that is already open"?

Is there an easy way to list all the available output ports to connect an input to?

This test works well for what I want! I just wanted a sanity unit test for the wrapper class I'm putting around the mido stuff.

**Comment by olemb** [comment]
Yes, that's it. (`create_port()` would probably be a clearer API.)

The names have to be the same. You can call `mido.get_input_names()` to get a list of available ports, or if you're on Linux or Mac you use `mido-ports` on the command line. (This program doesn't install correctly on Windows but you can find it in the repository.)

(Note that on Linux the port names will include the client name and ALSA port number, for example: `'RtMidiIn Client:send port 129:0'`. You can leave these out when opening the port in Mido.)

**Comment by cjappl** [comment]
Sweet, much appreciated!

**Comment by cjappl** [comment]
Is there a reason to use `receive` over `poll`? Or a reason that `poll` wouldn't work?

**Comment by olemb** [comment]
`receive()` will always wait for the message to arrive before returning. With `poll()` there is a chance that the message is still stuck in a buffer somewhere or being processed by another thread when you call `poll()`.

I've been testing a bit here running `send()` and `poll()` in a tight loop and I haven't lost a message yet so it doesn't seem to make a difference in this case, but there is a chance that it could fail in the future if the plementation of RtMiid changes or you switch to another backend.

**Comment by cjappl** [comment]
Got it, may just be something that's slowing up the message by some small amount of time! Receive works every time without fail, poll may just be checking too fast.

Again, thanks for your insight.

**Comment by cjappl** [comment]
A couple more things while I have a thread:

I ran all unit tests on OSX 10.10.5 with Python 3.6 and everything is passing. I have yet to run into any issues with Python 3.6, if you ever need someone to test with this system config, don't hesitate to reach out.

I'm also happy to take on any issues or tasks, if you have some to assign. Seems like a great project to dig into!

Cheers

**Comment by olemb** [comment]
Thanks for offering to help out!

If you want to know where Mido is heading you can check out (what will eventually become) the [roadmap](https://mido.readthedocs.io/en/latest/roadmap.html). I don't know if there's anything there that you can jump right into but I appreciate any feedback you might have.

Feel free to comment on any open issue or create new ones of your own if you have ideas or feel that something could be changed or improved.

**Comment by cjappl** [comment]
Great, will do. For the record, I'm a QA Automation engineer that works in pytest every day. If you need any help on the testing side of the package, that'd be my expertise, but I'm happy to help with anything that comes up! 

I'll poke around and learn a bit more in the meantime.

**Comment by Josema23** [comment]
Hi, I'm trying to play some Midi files at the same time, is there any way to do that? I've been trying for a long time and I can't find the way.
